
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp2 # or gp3, io1, etc.
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
