name: wordpress Deployment to EKS
on: 
  push: 
    branches: 
      - wordpress

jobs: 
  wordpress-deployment:
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_KEY }}


      - name: "Install kubectl"
        uses: azure/setup-kubectl@v3
        with: 
            version: "v1.19.3"
        id: "install-kubectl"


      - name: "Install Helm"
        uses: azure/setup-helm@v4.2.0
        id: "install-helm"

      - name: "Connect to the cluster"
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-cluster

      ### deploy wordpress using bitnami helm chart    

      - name: "Helm to Deploy Wordpress"
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install my-wp2 oci://registry-1.docker.io/bitnamicharts/wordpress \
            --set service.type=LoadBalancer \
            --set service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"=nlb \
            --set wordpressUsername=admin \
            --set wordpressPassword=password \
            --set wordpressScheme=https

      ### send logs to spluk

      - name: Send logs to Splunk
        env:
          SPLUNK_URL: ${{ secrets.SPLUNK_URL }}
          SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}
        run: |
          echo "Starting log shipment to Splunk"

          LOG_MESSAGE="GitHub Actions workflow triggered on push to main"
          PAYLOAD="{\"event\": \"${LOG_MESSAGE}\", \"sourcetype\": \"github_actions\", \"index\": \"main\"}"

          curl -k -H "Authorization: Splunk $SPLUNK_TOKEN" \
               -d "$PAYLOAD" \
               $SPLUNK_URL/services/collector

          echo "Logs sent to Splunk"
 
          
  
       
